# Generated by Django 3.2.5 on 2021-12-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='用户主键', primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=32, unique=True)),
                ('password', models.CharField(db_index=True, help_text='密码', max_length=256)),
            ],
        ),
    ]
