# Generated by Django 3.2.5 on 2021-12-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(help_text='主键', primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(db_index=True, help_text='用户名', max_length=32, unique=True)),
                ('password', models.CharField(db_index=True, help_text='密码', max_length=256)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
